### ISSUE TITLE
Nested Grids?

### ISSUE THREAD

**Issue by jrista** [sdras/cssgridgenerator#27]
This is really a feature request. I love the simplicity of your tool, for quick and dirty grid configuration I love it! It has some quirks, most of which I think already have issues, but overall it is really nice how simple and easy it is to use. 

I am wondering, though...could this be extended, without losing the simple design...to support nested grid layouts?

**Comment by sdras** [comment]
Yeah, I've thought about that. I want to think of a way to do it that isn't too disruptive to the simplicity of the tool for beginners. Let me mull it over, I think I'll do it though :) thanks for filing

**Comment by jrista** [comment]
Aye, definitely agreed that the simplicity of the tool should be preserved. That is what is great about it (even for us non-beginners...being able to quickly generate grid css is great!)

**Comment by sdras** [comment]
Hey there! I thought about it some, and even though it's a nice idea, I want to keep it simple so that people don't get confused. I get a lot of happy feedback that they can easily understand this thing, and am working hard to not make it confusing. If I sacrifice the simplicity for any functionality, it will be media queries. Appreciate the thought, though!
