### ISSUE TITLE
Output CSS + HTML in "Your Grid Code" window

### ISSUE THREAD

**Issue by pedroposada** [sdras/cssgridgenerator#60]
Would it be possible to get the html markup as well as the css code when you click on the button for `Please may I have some code` ?

Basically, make the html markup available as well so that its very simple to copy paste into a file and preview it

Thanks for the great website. This is really helping me to get started with CSS grids 👍

**Comment by sdras** [comment]
You're the second person to ask for this so I think it might be a good idea. Previously I didn't add it because the HTML markup should be pretty straightforward, but the tool should be suitable for everyone and straightforward, so I stand corrected :)

I'll implement it eventually, pretty busy at the moment. Open to PRs.

**Comment by sdras** [comment]
done! thank you for the contribution!
