### ISSUE TITLE
Transparent Div after ".div21"

### ISSUE THREAD

**Issue by Ademking** [sdras/cssgridgenerator#62]
When you click to create a new div, you will get a colorful div
when you have more than 21 div it will be transparent with no colors
see this :
![image](https://user-images.githubusercontent.com/12462188/60391195-a26e4c00-9ae0-11e9-98d8-8c2d40a95434.png)

i think the problem is here:
https://github.com/sdras/cssgridgenerator/blob/f4ec8a4b2cd72c3c28433d68905a9fa434f1208c/src/components/AppGrid.vue#L171

What do you think ?

**Comment by sdras** [comment]
yeah it's the sass loop. I honestly didn't think someone would go beyond 20 lol. I can refactor it.

**Comment by Ademking** [comment]
@sdras you're right 👍 
anyway.. you made a cool website ❤️ thank you so much .. keep up the good work

**Comment by tripti1410** [comment]
@sdras hey, I want to raise PR for this issue. I just wanted to know what limit we should keep ? I am thinking of 50.

**Comment by sdras** [comment]
Yeah! Let's do 50. Any more than that and I honestly can't recommend they do that (I think even 20 is pushing it) Thanks @tripti1410!

**Comment by sdras** [comment]
I commented on the PR here, but I'm starting to think this is a bad idea. Why are you going above 20 divs? Do you know that content can flow in grid, you don't have to place each div the way you're doing, it will just flow. This is for very specific layouts. I'm not sure I should be supporting people doing things like this because it's an antipattern. I'm going to close this out, sorry @tripti1410 for your troubles.
